### PR TITLE
Bump leancode_lint dev dependency to 11 to enable compatibility with dart 3.3 (flutter >=3.19)

### PR DESCRIPTION
**Pull request by kotertom**

### CODE REVIEW

**Comment by kotertom** [comment]
fyi the change does not require publishing a new version. It only affects contributors and CI

**Comment by kotertom** [comment]
nevermind, it won't work on lower sdks after all 🤦 A bit of a bummer to have to tighten version constraints due to a dev dependency

**Comment by shilangyu** [comment]
What is the status here?

**Comment by kotertom** [comment]
Closing in favor of #291

**Pull request closed without merging**
