### PR TITLE
Enable new dart 2.18 lints 

### LINKED ISSUE #79: Evaluate new lints from Dart 2.18
- new: [`discarded_futures`](https://dart-lang.github.io/linter/lints/discarded_futures.html)
- new: [`unnecessary_to_list_in_spreads`](https://dart-lang.github.io/linter/lints/unnecessary_to_list_in_spreads.html)
- update: `use_colored_box` does not flag nullable colors
- new:  [`unnecessary_null_aware_operator_on_extension_on_nullable`](https://dart-lang.github.io/linter/lints/unnecessary_null_aware_operator_on_extension_on_nullable.html)

[Dart 2.18 changelogs](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#2180)

### LINKED ISSUE #80: Evaluate new lints from Dart 2.19
- new: [`collection_methods_unrelated_type`](https://dart-lang.github.io/linter/lints/collection_methods_unrelated_type.html)
- new: [`combinators_ordering`](https://dart-lang.github.io/linter/lints/combinators_ordering.html)
- new: [`dangling_library_doc_comments`](https://dart-lang.github.io/linter/lints/dangling_library_doc_comments.html)
- new: [`enable_null_safety`](https://dart-lang.github.io/linter/lints/enable_null_safety.html)
- new: [`implicit_call_tearoffs`](https://dart-lang.github.io/linter/lints/implicit_call_tearoffs.html)
- new: [`library_annotations`](https://dart-lang.github.io/linter/lints/library_annotations.html)
- new: [`unnecessary_library_directive`](https://dart-lang.github.io/linter/lints/unnecessary_library_directive.html)
- new: [`unreachable_from_main`](https://dart-lang.github.io/linter/lints/unreachable_from_main.html)
- new: [`use_string_in_part_of_directives`](https://dart-lang.github.io/linter/lints/use_string_in_part_of_directives.html)
- changed: [`use_colored_box`](https://dart-lang.github.io/linter/lints/use_colored_box.html) and [`use_decorated_box`](https://dart-lang.github.io/linter/lints/use_decorated_box.html) to not over-report on containers without a child.

### PR DESCRIPTION
**Pull request by shilangyu**
closes #79

### CODE REVIEW

**Review by bartekpacia — APPROVED** [review]

**Comment by bartekpacia** [comment]
Since these lints require Dart 2.18, shouldn't we bump major version to avoid breaking dependents?

**Comment by shilangyu** [comment]
They do not require dart 2.18

**Comment by bartekpacia** [comment]
So how do they work on older Dart versions?

**Comment by bartekpacia** [comment]
Let's get this merged and if any problems will appear, we'll just fix it.

**Pull request merged**
