### PR TITLE
Remove backend from force-update directory

### PR DESCRIPTION
**Pull request by KamilSztandur**

### CODE REVIEW

**Review by PiotrRogulski — APPROVED** [review]

**Comment by gogolon** [comment]
not sure if `contracts_generator.yaml` should be left unchanged as the path to contracts does not exist anymore

**Review by shilangyu — CHANGES_REQUESTED** [review]
Please do not merge, this is not correct.

**Comment by shilangyu** [comment]
Is there a blocker?

**Comment by KamilSztandur** [comment]
@shilangyu No, I just forgot about this one. Sorry

**Pull request merged**
