### PR TITLE
Bump leancode_lint in all packages

### PR DESCRIPTION
**Pull request by shilangyu**
Not adding changelog entries. This does not affect any downstream users.

### CODE REVIEW

**Review by bartekpacia — APPROVED** [review]

**Comment by Albert221** [comment]
Please add the changelog entry for the sake of completeness. It clearly explains why a new version was made, without holes in the log

**Comment by shilangyu** [comment]
But no new version is being made, I don't plan to release any of the packages. But I can add a changelog entry nonetheless.

**Comment by Albert221** [comment]
Yes, please add that note to some `Unreleased` header. Devs that will be releasing new version won't necessarily know/spot other changes made since last release if not that

**Comment by shilangyu** [comment]
@Albert221 bump

**Review by Albert221 — APPROVED** [review]

**Pull request merged**
